version: '3.9'
services:
  expressapp:
    container_name: expressapp
    build: ./server
    expose:
      - 8000
    volumes:
      - ./server:/usr/src/app
    networks:
      - meli-network
  reactapp:
    container_name: reactapp
    build: ./client
    expose:
      - 5000
    volumes:
      - ./client:/usr/src/app
    networks:
      - meli-network
  nginx:
    build: ./nginx
    ports:
      - 80:80
    links:
      - expressapp
      - reactapp
    restart: always
    networks:
      - meli-network
networks:
  meli-network:
    driver: bridge